import { type InsertQuestTemplate } from "@shared/schema";

export const SEED_QUESTS: InsertQuestTemplate[] = [
  // === SOCIAL ===
  { skill: "Social", text: "Give a genuine compliment to someone today.", difficulty: "Chill", xp: 5, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Social", text: "Ask one thoughtful question in your next interaction.", difficulty: "Chill", xp: 8, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Social", text: "Spend 10 minutes catching up with a family member.", difficulty: "Chill", xp: 10, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Social", text: "Send a thoughtful message to a friend you haven't spoken to in a while.", difficulty: "Balanced", xp: 15, isBoss: false, active: true, minSkillLevel: 3 },
  { skill: "Social", text: "Practice active listening in your next conversation.", difficulty: "Balanced", xp: 20, isBoss: false, active: true, minSkillLevel: 3 },
  { skill: "Social", text: "Share something personal in a safe conversation.", difficulty: "Balanced", xp: 20, isBoss: false, active: true, minSkillLevel: 5 },
  { skill: "Social", text: "Write a thank-you note to someone who helped you recently.", difficulty: "Balanced", xp: 25, isBoss: false, active: true, minSkillLevel: 5 },
  { skill: "Social", text: "Try starting a short conversation with someone new today.", difficulty: "Spicy", xp: 35, isBoss: false, active: true, minSkillLevel: 7 },
  { skill: "Social", text: "Introduce yourself to someone in a new setting.", difficulty: "Spicy", xp: 40, isBoss: false, active: true, minSkillLevel: 8 },
  { skill: "Social", text: "Invite someone for a coffee or a short walk.", difficulty: "Spicy", xp: 50, isBoss: false, active: true, minSkillLevel: 10 },
  { skill: "Social", text: "Host a small gathering or game night with friends.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 5 },
  { skill: "Social", text: "Have a 2-sentence exchange with a barista, cashier, or store employee that goes beyond ordering.", difficulty: "Chill", xp: 10, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Social", text: "Speak to one person today that you have never spoken to before. Minimum: 1 question + 1 follow-up.", difficulty: "Balanced", xp: 20, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Social", text: "In your next small talk moment, keep the conversation going 30 seconds longer than you normally would.", difficulty: "Balanced", xp: 15, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Social", text: "Use something happening around you (line, office moment, event, etc.) to start a short conversation.", difficulty: "Balanced", xp: 20, isBoss: false, active: true, minSkillLevel: 2 },
  { skill: "Social", text: "Be the first person to say hello in a setting where you normally wait.", difficulty: "Chill", xp: 8, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Social", text: "Talk to someone you see regularly but have never spoken to (gym, office, building, café).", difficulty: "Balanced", xp: 20, isBoss: false, active: true, minSkillLevel: 2 },
  { skill: "Social", text: 'Instead of "How are you?", ask one specific question like "What\'s been interesting today?" or "What\'s keeping you busy lately?"', difficulty: "Chill", xp: 10, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Social", text: "Share one small personal detail during a conversation (a preference, opinion, or tiny story).", difficulty: "Balanced", xp: 20, isBoss: false, active: true, minSkillLevel: 2 },
  { skill: "Social", text: "Talk to someone at work outside your immediate team for at least 2 minutes.", difficulty: "Spicy", xp: 35, isBoss: false, active: true, minSkillLevel: 2 },
  { skill: "Social", text: "Ask someone for a small recommendation (food, show, local spot, etc.) and respond to their answer.", difficulty: "Chill", xp: 10, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Social", text: "In any social setting today, be the first person to start a conversation with someone new.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },
  { skill: "Social", text: "Send one specific invite (time and place) without softening it. Keep it direct.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },
  { skill: "Social", text: "In a group, shift the conversation by introducing a new topic or question.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },
  { skill: "Social", text: "Introduce yourself confidently to someone you find slightly intimidating.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },
  { skill: "Social", text: "Pull together 2 or more people for something spontaneous and make it happen today.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },

  // === CAREER ===
  { skill: "Career", text: "Organize your workspace for better focus.", difficulty: "Chill", xp: 5, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Career", text: "Read an article about trends in your industry.", difficulty: "Chill", xp: 8, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Career", text: "Write down 3 professional goals for this month.", difficulty: "Chill", xp: 10, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Career", text: "Spend 15 minutes on a skill you want to develop.", difficulty: "Balanced", xp: 15, isBoss: false, active: true, minSkillLevel: 3 },
  { skill: "Career", text: "Spend 20 minutes learning something new related to your field.", difficulty: "Balanced", xp: 20, isBoss: false, active: true, minSkillLevel: 3 },
  { skill: "Career", text: "Block 30 minutes for deep, uninterrupted work.", difficulty: "Balanced", xp: 20, isBoss: false, active: true, minSkillLevel: 5 },
  { skill: "Career", text: "Draft a plan for a project you've been putting off.", difficulty: "Balanced", xp: 25, isBoss: false, active: true, minSkillLevel: 5 },
  { skill: "Career", text: "Ask for feedback on a recent piece of work.", difficulty: "Spicy", xp: 35, isBoss: false, active: true, minSkillLevel: 7 },
  { skill: "Career", text: "Reach out to a professional contact to check in.", difficulty: "Spicy", xp: 40, isBoss: false, active: true, minSkillLevel: 8 },
  { skill: "Career", text: "Update one section of your resume or portfolio.", difficulty: "Spicy", xp: 50, isBoss: false, active: true, minSkillLevel: 10 },
  { skill: "Career", text: "Apply to a new opportunity or pitch an idea to your team.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 5 },
  { skill: "Career", text: "One-Slide Power Move: Create a single-slide (or screenshot) proposal to improve something at work and send it to the right channel today.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },
  { skill: "Career", text: "Lightning Demo: Show someone (or record a 60-sec walkthrough) of something you built/learned/figured out this week—no prep, just ship it.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },
  { skill: "Career", text: "Question Upgrade: In your next meeting, ask one sharp question that changes the direction of the discussion.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },

  // === HEALTH ===
  { skill: "Health", text: "Take 3 slow, deep breaths before your next meal.", difficulty: "Chill", xp: 5, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Health", text: "Drink 8 glasses of water today.", difficulty: "Chill", xp: 8, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Health", text: "Eat a piece of fruit as a snack today.", difficulty: "Chill", xp: 8, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Health", text: "Take the stairs instead of the elevator today.", difficulty: "Chill", xp: 10, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Health", text: "Do a 5-minute stretching routine.", difficulty: "Balanced", xp: 15, isBoss: false, active: true, minSkillLevel: 3 },
  { skill: "Health", text: "Take a 10-minute walk without distractions.", difficulty: "Balanced", xp: 20, isBoss: false, active: true, minSkillLevel: 3 },
  { skill: "Health", text: "Do 10 push-ups or sit-ups right now.", difficulty: "Balanced", xp: 20, isBoss: false, active: true, minSkillLevel: 5 },
  { skill: "Health", text: "Spend 10 minutes doing light exercise.", difficulty: "Balanced", xp: 25, isBoss: false, active: true, minSkillLevel: 5 },
  { skill: "Health", text: "Prepare a healthy meal from scratch.", difficulty: "Spicy", xp: 40, isBoss: false, active: true, minSkillLevel: 8 },
  { skill: "Health", text: "Go to bed 30 minutes earlier tonight.", difficulty: "Spicy", xp: 35, isBoss: false, active: true, minSkillLevel: 7 },
  { skill: "Health", text: "Complete a full 30-minute workout session.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 5 },
  { skill: "Health", text: "Step Boss: Hit 8,000 steps today—your last 1,000 must be outside after dinner.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },
  { skill: "Health", text: "Sweat Ladder: Do 10 squats + 10 push-ups + 30-sec plank. Repeat the ladder 3 times (rest allowed).", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },
  { skill: "Health", text: "Two-Color Plate: Build one meal using only two main colors of whole foods (example: green + red). No ultra-processed sides.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },

  // === MIND ===
  { skill: "Mind", text: "Write down one thing you learned today.", difficulty: "Chill", xp: 5, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Mind", text: "Try a short breathing exercise to relax.", difficulty: "Chill", xp: 8, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Mind", text: "Spend 10 minutes without any screens.", difficulty: "Chill", xp: 10, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Mind", text: "Write down 3 things you are grateful for.", difficulty: "Balanced", xp: 15, isBoss: false, active: true, minSkillLevel: 3 },
  { skill: "Mind", text: "Meditate for 5 minutes today.", difficulty: "Balanced", xp: 15, isBoss: false, active: true, minSkillLevel: 3 },
  { skill: "Mind", text: "Solve a puzzle or brain teaser.", difficulty: "Balanced", xp: 20, isBoss: false, active: true, minSkillLevel: 5 },
  { skill: "Mind", text: "Reflect on a recent challenge and what you learned from it.", difficulty: "Balanced", xp: 25, isBoss: false, active: true, minSkillLevel: 5 },
  { skill: "Mind", text: "Read 10 pages of a book.", difficulty: "Spicy", xp: 35, isBoss: false, active: true, minSkillLevel: 7 },
  { skill: "Mind", text: "Spend 15 minutes journaling about your day.", difficulty: "Spicy", xp: 40, isBoss: false, active: true, minSkillLevel: 8 },
  { skill: "Mind", text: "Watch a documentary about something you are curious about.", difficulty: "Spicy", xp: 50, isBoss: false, active: true, minSkillLevel: 10 },
  { skill: "Mind", text: "Read an entire chapter of a non-fiction book and write a summary.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 5 },
  { skill: "Mind", text: "No-Scroll Fortress: Block social feeds for a 3-hour window today and replace it with one intentional activity.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },
  { skill: "Mind", text: "Curiosity Rabbit Hole: Learn one new topic for 20 minutes, then write 5 bullets + 1 analogy that makes it easy.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },
  { skill: "Mind", text: "Explain Like I'm 5: Take a concept you know and explain it to someone in 5 simple sentences.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },

  // === CREATIVITY ===
  { skill: "Creativity", text: "Doodle freely for 5 minutes without lifting your pen.", difficulty: "Chill", xp: 5, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Creativity", text: "Listen to a genre of music you don't usually explore.", difficulty: "Chill", xp: 8, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Creativity", text: "Take a photo of something beautiful you notice today.", difficulty: "Chill", xp: 10, isBoss: false, active: true, minSkillLevel: 1 },
  { skill: "Creativity", text: "Brainstorm 5 ideas for a fun side project.", difficulty: "Balanced", xp: 15, isBoss: false, active: true, minSkillLevel: 3 },
  { skill: "Creativity", text: "Try a new creative tool or app for 15 minutes.", difficulty: "Balanced", xp: 20, isBoss: false, active: true, minSkillLevel: 3 },
  { skill: "Creativity", text: "Write a short poem or haiku.", difficulty: "Balanced", xp: 20, isBoss: false, active: true, minSkillLevel: 5 },
  { skill: "Creativity", text: "Rearrange or decorate a small space in your home.", difficulty: "Balanced", xp: 25, isBoss: false, active: true, minSkillLevel: 5 },
  { skill: "Creativity", text: "Sketch something simple for 10 minutes.", difficulty: "Spicy", xp: 35, isBoss: false, active: true, minSkillLevel: 7 },
  { skill: "Creativity", text: "Try cooking a recipe you have never made before.", difficulty: "Spicy", xp: 40, isBoss: false, active: true, minSkillLevel: 8 },
  { skill: "Creativity", text: "Write a short story in 100 words or less.", difficulty: "Spicy", xp: 50, isBoss: false, active: true, minSkillLevel: 10 },
  { skill: "Creativity", text: "Create a complete piece of art, writing, or music from scratch.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 5 },
  { skill: "Creativity", text: "Constraint Creator: Create something using 3 random words you see around you (title must include all 3).", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },
  { skill: "Creativity", text: "Remix Boss: Take an old idea/draft and improve it in one bold way, then show it to one person.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },
  { skill: "Creativity", text: "Public Drop: Share a rough creation today (post, sketch, snippet, demo). No perfection pass.", difficulty: "Spicy", xp: 50, isBoss: true, active: true, minSkillLevel: 1 },
];
